---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      project: "kafka"
      provider: "debezium"
      version: "0.3-SNAPSHOT"
      group: "io.debezium"
    name: "kafka"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 9092
      protocol: "TCP"
      targetPort: 9092
    selector:
      project: "kafka"
      provider: "debezium"
      group: "io.debezium"
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-branch: "0.2-SNAPSHOT"
      fabric8.io/git-commit: "e29bd9752f12c166fb989fabebc9cfb3bba4e331"
    labels:
      project: "kafka"
      provider: "debezium"
      version: "0.3-SNAPSHOT"
      group: "io.debezium"
    name: "kafka"
  spec:
    replicas: 1
    selector:
      project: "kafka"
      provider: "debezium"
      version: "0.3-SNAPSHOT"
      group: "io.debezium"
    template:
      metadata:
        annotations: {}
        labels:
          project: "kafka"
          provider: "debezium"
          version: "0.3-SNAPSHOT"
          group: "io.debezium"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "KAFKA_ADVERTISED_PORT"
            value: "9092"
          - name: "KAFKA_ADVERTISED_HOST_NAME"
            value: "kafka"
          - name: "KAFKA_ZOOKEEPER_CONNECT"
            value: "zookeeper:2181"
          - name: "KAFKA_PORT"
            value: "9092"
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "docker.io/debezium/kafka:0.3"
          imagePullPolicy: "IfNotPresent"
          name: "kafka"
          ports:
          - containerPort: 9092
            name: "plaintext"
          securityContext: {}
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        volumes: []
kind: "List"
